application: todo-map
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app

- url: /$
  static_files: app/index.html
  upload: app/$

- url: /(.*)/$
  static_files: app/\1/index.html
  upload: app/(.*)/$

- url: /
  static_dir: app